name: Main workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
      - release
      - master
    types: [opened, synchronize]
jobs:
  deploy:
    name: Connect to Amazon S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::473024607515:user/weilun.huang
        aws-region: ap-northeast-1
    - name: list EC2
      run: |
        aws ec2 describe-instances --filters "Name=tag:Name,Values=roo-github-actions-runner"
